### ISSUE TITLE
Error when install

### ISSUE THREAD

**Issue by dynamotn** [0xd3adcafe/willie-lumberjack#2]
When execute command: "pip install requirements.txt" i receive that:

Downloading/unpacking requirements.txt
  Real name of requirement requirements.txt is requirements.txt
  Could not find any downloads that satisfy the requirement requirements.txt
Cleaning up...
No distributions at all found for requirements.txt
Storing complete log in /root/.pip/pip.log

**Comment by N3bTcx** [comment]
Hello

Have you try with the full path? like `pip install /home/user/willie/requirements.txt` ?

Could you add more verbose (`pip -v install requirements.txt`)?

**Comment by jinpark** [comment]
I think this is supposed to be `pip install -r requirements.txt`
